/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/send-verification-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Verification Code
         * @description Send verification code to email
         */
        post: operations["send_verification_code_auth_send_verification_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Email Code
         * @description Verify the email verification code and create user account
         */
        post: operations["verify_email_code_auth_verify_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/twitter/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Twitter Login
         * @description Initiate Twitter OAuth login flow with PKCE
         */
        get: operations["twitter_login_auth_twitter_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/twitter/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Twitter Callback
         * @description Handle Twitter OAuth callback
         */
        get: operations["twitter_callback_auth_twitter_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Login
         * @description Initiate Google OAuth login flow
         */
        get: operations["google_login_auth_google_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description Handle Google OAuth callback
         */
        get: operations["google_callback_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Presets
         * @description Get all available presets
         */
        get: operations["get_presets_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preset
         * @description Get a specific preset by ID
         */
        get: operations["get_preset_presets__preset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Profile
         * @description Get current user profile with subscription info
         */
        get: operations["get_current_user_profile_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Statistics
         * @description Get current user statistics
         */
        get: operations["get_current_user_statistics_users_me_statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Subscription
         * @description Create or update subscription for current user
         */
        post: operations["create_subscription_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Subscription
         * @description Get subscription for current user
         */
        get: operations["get_current_user_subscription_subscriptions_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Svg */
        post: operations["generate_svg_v1_svg_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/svgs/{svg_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Svg By Id
         * @description Get a specific SVG by ID (only if owned by user or public)
         */
        get: operations["get_svg_by_id_svgs__svg_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Svg
         * @description Delete a specific SVG.
         *     Only the owner of the generation containing this SVG can delete it.
         */
        delete: operations["delete_svg_svgs__svg_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enhance-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enhance Prompt
         * @description Enhance a prompt using OpenAI
         */
        post: operations["enhance_prompt_v1_enhance_prompt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explore Generations
         * @description Search for public SVG generations based on a query.
         *     Searches through prompts, styles, and labels.
         */
        post: operations["explore_generations_explore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Generations
         * @description Get all generations for current user with pagination
         */
        get: operations["get_current_user_generations_generations_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generations/{generation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Generation Details
         * @description Get a specific generation with all its SVGs
         */
        get: operations["get_generation_details_generations__generation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /** AuthStateResponse */
        AuthStateResponse: {
            /** Auth Url */
            auth_url: string;
            /** State */
            state: string;
        };
        /** EmailVerificationCodeRequest */
        EmailVerificationCodeRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Code */
            code: string;
        };
        /** EmailVerificationRequest */
        EmailVerificationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ExploreRequest */
        ExploreRequest: {
            /**
             * Query
             * @description Search query
             * @default
             */
            query: string;
            /**
             * Page
             * @description Page number (starting from 1)
             */
            page?: number | null;
            /**
             * Limit
             * @description Maximum number of results
             * @default 20
             */
            limit: number;
            /**
             * Offset
             * @description Offset for pagination
             */
            offset?: number | null;
        };
        /** GenerationResponse */
        GenerationResponse: {
            /** Id */
            id: number;
            /** Prompt */
            prompt: string;
            /** Style */
            style: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Svgs
             * @default []
             */
            svgs: components["schemas"]["SVGResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PresetResponse */
        PresetResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
            /** Style */
            style: string;
        };
        /** PromptEnhanceRequest */
        PromptEnhanceRequest: {
            /**
             * Prompt
             * @description Simple prompt to be enhanced
             */
            prompt: string;
            /**
             * Style
             * @description Target style for the SVG
             * @default vector_illustration
             * @enum {string}
             */
            style: "icon" | "vector_illustration";
        };
        /** PromptEnhanceResponse */
        PromptEnhanceResponse: {
            /** Enhanced Prompt */
            enhanced_prompt: string;
        };
        /** SVGGenerationRequest */
        SVGGenerationRequest: {
            /**
             * Prompt
             * @description Text prompt for SVG generation
             */
            prompt: string;
            /**
             * Size
             * @description Output image size
             * @default 1024x1024
             */
            size: string;
            /**
             * Style
             * @description Style for the generated SVG.
             * @default vector_illustration
             * @enum {string}
             */
            style: "vector_illustration" | "vector_illustration/cartoon" | "vector_illustration/doodle_line_art" | "vector_illustration/engraving" | "vector_illustration/flat_2" | "vector_illustration/kawaii" | "vector_illustration/line_art" | "vector_illustration/line_circuit" | "vector_illustration/linocut" | "vector_illustration/seamless" | "icon" | "icon/broken_line" | "icon/colored_outline" | "icon/colored_shapes" | "icon/colored_shapes_gradient" | "icon/doodle_fill" | "icon/doodle_offset_fill" | "icon/offset_fill" | "icon/outline" | "icon/outline_gradient" | "icon/uneven_fill";
            /**
             * Aspect Ratio
             * @description Aspect ratio setting
             * @default Not set
             */
            aspect_ratio: string;
            /**
             * Preset Id
             * @description Preset ID to use
             */
            preset_id?: string | null;
            /**
             * Label
             * @description Optional label for the SVG
             */
            label?: string | null;
            /**
             * Public
             * @description Whether the SVG should be public
             * @default true
             */
            public: boolean;
            /**
             * Count
             * @description Number of SVGs to generate
             * @default 1
             */
            count: number;
        };
        /** SVGResponse */
        SVGResponse: {
            /** Id */
            id: number;
            /** Generation Id */
            generation_id: number;
            /** Content */
            content: string;
            /** Label */
            label: string | null;
            /** Public */
            public: boolean;
        };
        /** SubscriptionCreate */
        SubscriptionCreate: {
            /** @default free */
            tier: components["schemas"]["SubscriptionTier"];
            /** Payment Info */
            payment_info?: string | null;
            /** To Date */
            to_date?: string | null;
        };
        /** SubscriptionResponse */
        SubscriptionResponse: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            tier: components["schemas"]["SubscriptionTier"];
            /** Payment Info */
            payment_info: string | null;
            /**
             * From Date
             * Format: date-time
             */
            from_date: string;
            /** To Date */
            to_date: string | null;
        };
        /**
         * SubscriptionTier
         * @enum {string}
         */
        SubscriptionTier: "free" | "base" | "pro";
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string | null;
            /** Generation Limit */
            generation_limit: number;
            /** Private Limit */
            private_limit: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserStatistics */
        UserStatistics: {
            /** Total Generations */
            total_generations: number;
            /** Total Svgs */
            total_svgs: number;
            /** Public Svgs */
            public_svgs: number;
            /** Private Svgs */
            private_svgs: number;
            /** Generation Limit */
            generation_limit: number;
            /** Private Limit */
            private_limit: number;
            /** Generations Remaining */
            generations_remaining: number;
            /** Private Svgs Remaining */
            private_svgs_remaining: number;
        };
        /** UserWithRelations */
        UserWithRelations: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string | null;
            /** Generation Limit */
            generation_limit: number;
            /** Private Limit */
            private_limit: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            subscription?: components["schemas"]["SubscriptionResponse"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    send_verification_code_auth_send_verification_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_code_auth_verify_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailVerificationCodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    twitter_login_auth_twitter_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStateResponse"];
                };
            };
        };
    };
    twitter_callback_auth_twitter_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_login_auth_google_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStateResponse"];
                };
            };
        };
    };
    google_callback_auth_google_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_presets_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"][];
                };
            };
        };
    };
    get_preset_presets__preset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_profile_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithRelations"];
                };
            };
        };
    };
    get_current_user_statistics_users_me_statistics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStatistics"];
                };
            };
        };
    };
    create_subscription_subscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_subscription_subscriptions_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
        };
    };
    generate_svg_v1_svg_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SVGGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_svg_by_id_svgs__svg_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                svg_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SVGResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_svg_svgs__svg_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                svg_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enhance_prompt_v1_enhance_prompt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptEnhanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptEnhanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_generations_explore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExploreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_generations_generations_me_get: {
        parameters: {
            query?: {
                /** @description Page number (starting from 1) */
                page?: number | null;
                /** @description Number of results per page */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_details_generations__generation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
