/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Svg Raw */
        post: operations["generate_svg_raw_v1_svg_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enhance-prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enhance Prompt */
        post: operations["enhance_prompt_v1_enhance_prompt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PromptEnhanceRequest
         * @example {
         *       "prompt": "Simple superman icon",
         *       "style": "icon"
         *     }
         */
        PromptEnhanceRequest: {
            /**
             * Prompt
             * @description Simple prompt to be enhanced
             */
            prompt: string;
            /**
             * Style
             * @description Target style for the SVG (helps tailor the enhancement)
             * @default vector_illustration
             * @enum {string}
             */
            style: "icon" | "vector_illustration";
        };
        /** PromptEnhanceResponse */
        PromptEnhanceResponse: {
            /** Enhanced Prompt */
            enhanced_prompt: string;
        };
        /**
         * SVGGenerationRequest
         * @example {
         *       "aspect_ratio": "Not set",
         *       "prompt": "a portrait of a cute red panda using a laptop, the poster has the title \"Red panda\", against a red background",
         *       "size": "1024x1024",
         *       "style": "vector_illustration"
         *     }
         */
        SVGGenerationRequest: {
            /**
             * Prompt
             * @description Text prompt for SVG generation
             */
            prompt: string;
            /**
             * Size
             * @description Output image size
             * @default 1024x1024
             */
            size: string;
            /**
             * Style
             * @description Style for the generated SVG. Must be one of the predefined styles.
             * @default vector_illustration
             * @enum {string}
             */
            style: "vector_illustration" | "vector_illustration/cartoon" | "vector_illustration/doodle_line_art" | "vector_illustration/engraving" | "vector_illustration/flat_2" | "vector_illustration/kawaii" | "vector_illustration/line_art" | "vector_illustration/line_circuit" | "vector_illustration/linocut" | "vector_illustration/seamless" | "icon" | "icon/broken_line" | "icon/colored_outline" | "icon/colored_shapes" | "icon/colored_shapes_gradient" | "icon/doodle_fill" | "icon/doodle_offset_fill" | "icon/offset_fill" | "icon/outline" | "icon/outline_gradient" | "icon/uneven_fill";
            /**
             * Aspect Ratio
             * @description Aspect ratio setting
             * @default Not set
             */
            aspect_ratio: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generate_svg_raw_v1_svg_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SVGGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enhance_prompt_v1_enhance_prompt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptEnhanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptEnhanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
